language: generic 

sudo: required
services:
  - docker
  
before_install:
  - docker build -t sri554278/docker-react-git -f Dockerfile.dev .
  
script:
  - docker run -e CI=true sri554278/docker-react-git npm run test
  
