version: '3'
services:
  frontend:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - .:/app      
    # Below to fix issue with exit code 0 in windows
    stdin_open: true
    # Below to run Windows not Detecting Changes - Docker Compose
    environment:
      - CHOKIDAR_USEPOLLING=true
  
  tests:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app
    command: ["npm", "run", "test"]
    # Below to fix issue with exit code 0 in windows
    stdin_open: true
    # Below to run Windows not Detecting Changes - Docker Compose
    environment:
      - CHOKIDAR_USEPOLLING=true